### ISSUE TITLE
Support environments in zelda.yml

### ISSUE THREAD

**Issue by ariejan** [ariejan/link#7]
Instead of juggling multiple configuration files, it might be easier to add multiple environments to a single config file. For example:

```
zelda:
  production:
    server_url: https://api.example.com
    username: <connect-link-integrator-username>
    password: <connect-link-integrator-password>
  acceptance:
    server_url: https://api.example.com
    username: <connect-link-integrator-username>
    password: <connect-link-integrator-password>
```

An additional flag can be used to select the environment. The first one can then be used as default. 

`zelda -e acceptance installations`
